- hosts: service_host
  vars:
    source_conf: ../scripts/tmp/conf-files
    target_conf: ./
  tasks:
    - name: Removing files from earlier installation in service_host
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "./conf-files"
        - "./deploy-and-start-services.sh"
    - name: Copying conf-files to service_host
      copy:
        src: "{{ source_conf }}"
        dest: "{{ target_conf }}"
        mode: 0600
    - name: Copying service.conf to service_host
      copy:
        src: "{{ source_conf }}/service.conf"
        dest: "{{ target_conf }}/conf-files/service.conf"
        mode: 0644
    - name: Copying deploy-and-start-services.sh to service_host
      copy:
        src: "../scripts/tmp/deploy-and-start-services.sh"
        dest: "./deploy-and-start-services.sh"
        mode: 0644
    - name: Copying start-eureca-frontend.sh to service_host
      copy:
        src: "../scripts/tmp/start-eureca-frontend.sh"
        dest: "./start-eureca-frontend.sh"
        mode: 0644
    - name: Copying start-eureca-backend.sh to service_host
      copy:
        src: "../scripts/tmp/start-eureca-backend.sh"
        dest: "./start-eureca-backend.sh"
        mode: 0644
    - name: Copying start-eureca-as.sh to service_host
      copy:
        src: "../scripts/tmp/start-eureca-as.sh"
        dest: "./start-eureca-as.sh"
        mode: 0644
    - name: Copying start-alumni-site.sh to service_host
      copy:
        src: "../scripts/tmp/start-alumni-site.sh"
        dest: "./start-alumni-site.sh"
        mode: 0644
    - name: Copying start-apache.sh to service_host
      copy:
        src: "../scripts/tmp/start-apache.sh"
        dest: "./start-apache.sh"
        mode: 0644
    - name: Copying start-alumni-backend.sh to service_host
      copy:
        src: "../scripts/tmp/start-alumni-backend.sh"
        dest: "./start-alumni-backend.sh"
        mode: 0644